plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
  //  alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

// Move the helper function to the top-level of the file
fun String.runCommand(workingDir: File): String? =
    try {
        ProcessBuilder(*split(" ").toTypedArray())
            .directory(workingDir)
            .redirectErrorStream(true)
            .start()
            .inputStream
            .bufferedReader()
            .readText()
            .trim()
    } catch (e: Exception) {
        null
    }

android {
    namespace = "com.example.compose"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.example.compose"
        minSdk = 25
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        
        // Get the hash once for use across the block
        val shortCommitHash = "git rev-parse --short HEAD".runCommand(project.rootDir) ?: "dev"
        versionNameSuffix = "-alpha-$shortCommitHash"
    }

    buildFeatures {
        compose = true
    }
    
    buildTypes {
        debug {
            isMinifyEnabled = false
            isDebuggable = true
            applicationIdSuffix = ".debug"
            
            // This adds to the existing "-alpha-hash" suffix
            versionNameSuffix = "-debug" 
            
            buildConfigField("String", "BUILD_VARIANT", "\"debug\"")
            buildConfigField("boolean", "ENABLE_LOGGING", "true")
        }
        
        /* getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            isDebuggable = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            // No need to redeclare hash here, it inherits from defaultConfig
        } */
    }


    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
  //  implementation(libs.androidx.navigation3)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}